<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <RootNamespace>Paradox_Editor</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="blank_world_map.png" />
    <None Remove="Preloaded_Assets\EU4\mapmode_ProvincesOff.png" />
    <None Remove="Preloaded_Assets\EU4\mapmode_ProvincesOn.png" />
    <None Remove="Preloaded_Assets\VIC2\mapmode_PoliticalOff.png" />
    <None Remove="Preloaded_Assets\VIC2\mapmode_PoliticalOn.png" />
    <None Remove="Preloaded_Assets\VIC2\mapmode_ProvincesOff.png" />
    <None Remove="Preloaded_Assets\VIC2\mapmode_ProvincesOn.png" />
    <None Remove="Preloaded_Assets\VIC2\mapmode_TerrainOff.png" />
    <None Remove="Preloaded_Assets\VIC2\mapmode_TerrainOn.png" />
    <None Remove="provinces.bmp" />
    <None Remove="provinces.png" />
    <None Remove="TestEnvironmentFolder\TestCountries.txt" />
    <None Remove="TestEnvironmentFolder\TestCountries\Jan Mayen.txt" />
    <None Remove="TestEnvironmentFolder\TestCountries\Mann.txt" />
    <None Remove="TestEnvironmentFolder\TestCountries\Pskov.txt" />
    <None Remove="TestProvince.bmp" />
    <None Remove="vic2_provinces.bmp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="27.1.1" />
    <PackageReference Include="Hangfire.Core" Version="1.7.24" />
    <PackageReference Include="System.Collections.NonGeneric" Version="4.3.0" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
    <PackageReference Include="WriteableBitmapEx" Version="1.6.8" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.Windows.Forms.dll</HintPath>
    </Reference>
    <Reference Include="WindowsFormsIntegration">
      <HintPath>..\..\..\..\..\Program Files\Reference Assemblies\Microsoft\Framework\v3.0\WindowsFormsIntegration.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="blank_world_map.png" />
    <Resource Include="Preloaded_Assets\EU4\Icons\mapmode_ProvincesOff.png" />
    <Resource Include="Preloaded_Assets\EU4\Icons\mapmode_ProvincesOn.png" />
    <Resource Include="Preloaded_Assets\VIC2\Icons\mapmode_PoliticalOff.png" />
    <Resource Include="Preloaded_Assets\VIC2\Icons\mapmode_PoliticalOn.png" />
    <Resource Include="Preloaded_Assets\VIC2\Icons\mapmode_ProvincesOff.png" />
    <Resource Include="Preloaded_Assets\VIC2\Icons\mapmode_ProvincesOn.png" />
    <Resource Include="Preloaded_Assets\VIC2\Icons\mapmode_TerrainOff.png" />
    <Resource Include="Preloaded_Assets\VIC2\Icons\mapmode_TerrainOn.png" />
    <Resource Include="Preloaded_Assets\VIC2\Sounds\VIC2_ValidClick.wav" />
    <Resource Include="TestEnvironmentFolder\TestCountries.txt" />
    <Resource Include="TestEnvironmentFolder\TestCountries\Jan Mayen.txt" />
    <Resource Include="TestEnvironmentFolder\TestCountries\Mann.txt" />
    <Resource Include="TestEnvironmentFolder\TestCountries\Pskov.txt" />
    <Resource Include="TestProvince.bmp" />
    <Resource Include="vic2_provinces.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Preloaded_Assets\EU4\Sounds\" />
    <Folder Include="TestEnvironmentFolder\TestProvinceFiles\provinces\" />
  </ItemGroup>

</Project>
