<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>Paradox_Editor</RootNamespace>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>zorg.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".editorconfig" />
    <None Remove="BackgroundSelectEU4.png" />
    <None Remove="BackgroundSelectVIC2.png" />
    <None Remove="blank_world_map.png" />
    <None Remove="Assets\EU4\Icons\button_add.png" />
    <None Remove="Assets\EU4\Icons\button_exit.png" />
    <None Remove="Assets\EU4\Icons\button_remove.png" />
    <None Remove="Assets\EU4\Icons\button_reset.png" />
    <None Remove="Assets\EU4\Icons\mapmode_PoliticalOff.png" />
    <None Remove="Assets\EU4\Icons\mapmode_PoliticalOn.png" />
    <None Remove="Assets\EU4\Icons\mapmode_TerrainOff.png" />
    <None Remove="Assets\EU4\Icons\mapmode_TerrainOn.png" />
    <None Remove="Assets\EU4\Images\provinceInterface.png" />
    <None Remove="Assets\EU4\mapmode_ProvincesOff.png" />
    <None Remove="Assets\EU4\mapmode_ProvincesOn.png" />
    <None Remove="Assets\EU4\Sounds\connecting.wav" />
    <None Remove="Assets\EU4\Sounds\validClick.wav" />
    <None Remove="Assets\save_confirm_button.gif" />
    <None Remove="Assets\save_notif_button.png" />
    <None Remove="Assets\VIC2\Icons\button_add.png" />
    <None Remove="Assets\VIC2\Icons\button_exit.png" />
    <None Remove="Assets\VIC2\Icons\button_remove.png" />
    <None Remove="Assets\VIC2\Icons\button_reset.png" />
    <None Remove="Assets\VIC2\Icons\VIC2_Exit.png" />
    <None Remove="Assets\VIC2\Images\main_bg.png" />
    <None Remove="Assets\VIC2\Images\provinceInterface.png" />
    <None Remove="Assets\VIC2\mapmode_PoliticalOff.png" />
    <None Remove="Assets\VIC2\mapmode_PoliticalOn.png" />
    <None Remove="Assets\VIC2\mapmode_ProvincesOff.png" />
    <None Remove="Assets\VIC2\mapmode_ProvincesOn.png" />
    <None Remove="Assets\VIC2\mapmode_TerrainOff.png" />
    <None Remove="Assets\VIC2\mapmode_TerrainOn.png" />
    <None Remove="Assets\VIC2\Sounds\connecting.wav" />
    <None Remove="provinces.bmp" />
    <None Remove="provinces.png" />
    <None Remove="save_warning_button.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="29.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0-rc.2.22472.3" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <PackageReference Include="WriteableBitmapEx" Version="1.6.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\BackgroundSelectEU4.png" />
    <Resource Include="Assets\blank_world_map.png" />
    <Resource Include="Assets\BackgroundSelectVIC2.png" />
    <Resource Include="Assets\EU4\Icons\button_add.png" />
    <Resource Include="Assets\EU4\Icons\button_exit.png" />
    <Resource Include="Assets\EU4\Icons\button_remove.png" />
    <Resource Include="Assets\EU4\Icons\button_reset.png" />
    <Resource Include="Assets\EU4\Icons\mapmode_PoliticalOff.png" />
    <Resource Include="Assets\EU4\Icons\mapmode_PoliticalOn.png" />
    <Resource Include="Assets\EU4\Icons\mapmode_ProvincesOff.png" />
    <Resource Include="Assets\EU4\Icons\mapmode_ProvincesOn.png" />
    <Resource Include="Assets\EU4\Icons\mapmode_TerrainOff.png" />
    <Resource Include="Assets\EU4\Icons\mapmode_TerrainOn.png" />
    <Resource Include="Assets\EU4\Images\provinceInterface.png" />
    <Resource Include="Assets\save_confirm_button.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\save_notif_button.png" />
    <Resource Include="Assets\VIC2\Icons\button_add.png" />
    <Resource Include="Assets\VIC2\Icons\button_exit.png" />
    <Resource Include="Assets\VIC2\Icons\button_remove.png" />
    <Resource Include="Assets\VIC2\Icons\button_reset.png" />
    <Resource Include="Assets\VIC2\Icons\mapmode_PoliticalOff.png" />
    <Resource Include="Assets\VIC2\Icons\mapmode_PoliticalOn.png" />
    <Resource Include="Assets\VIC2\Icons\mapmode_ProvincesOff.png" />
    <Resource Include="Assets\VIC2\Icons\mapmode_ProvincesOn.png" />
    <Resource Include="Assets\VIC2\Icons\mapmode_TerrainOff.png" />
    <Resource Include="Assets\VIC2\Icons\mapmode_TerrainOn.png" />
    <Resource Include="Assets\VIC2\Icons\VIC2_Exit.png" />
    <Resource Include="Assets\VIC2\Images\main_bg.png" />
    <Resource Include="Assets\VIC2\Images\provinceInterface.png" />
    <Resource Include="Assets\EU4\Sounds\connecting.wav" />
    <Resource Include="Assets\EU4\Sounds\validClick.wav" />
    <Resource Include="Assets\VIC2\Sounds\connecting.wav" />
    <Resource Include="Assets\VIC2\Sounds\validClick.wav" />
    <Resource Include="Assets\save_warning_button.gif" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\LukeZurg22_Gaming\source\repos\Paradox Editor\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\LukeZurg22_Gaming\source\repos\Paradox Editor\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="zorg.ico" />
  </ItemGroup>

</Project>
