<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <RootNamespace>Paradox_Editor</RootNamespace>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Prefer32Bit>true</Prefer32Bit>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="blank_world_map.png" />
    <None Remove="Preloaded_GFX\EU4\mapmode_ProvincesOff.png" />
    <None Remove="Preloaded_GFX\EU4\mapmode_ProvincesOn.png" />
    <None Remove="Preloaded_GFX\VIC2\mapmode_PoliticalOff.png" />
    <None Remove="Preloaded_GFX\VIC2\mapmode_PoliticalOn.png" />
    <None Remove="Preloaded_GFX\VIC2\mapmode_ProvincesOff.png" />
    <None Remove="Preloaded_GFX\VIC2\mapmode_ProvincesOn.png" />
    <None Remove="Preloaded_GFX\VIC2\mapmode_TerrainOff.png" />
    <None Remove="Preloaded_GFX\VIC2\mapmode_TerrainOn.png" />
    <None Remove="Preloaded_GFX\VIC2\VIC2_Buttons%280%29.png" />
    <None Remove="Preloaded_GFX\VIC2\VIC2_Buttons%281%29.png" />
    <None Remove="Preloaded_GFX\VIC2\VIC2_Buttons%282%29.png" />
    <None Remove="Preloaded_GFX\VIC2\VIC2_Buttons%283%29.png" />
    <None Remove="Preloaded_GFX\VIC2\VIC2_Buttons%284%29.png" />
    <None Remove="provinces.bmp" />
    <None Remove="provinces.png" />
    <None Remove="vic2_provinces.bmp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.7.24" />
    <PackageReference Include="System.Collections.NonGeneric" Version="4.3.0" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v3.5\Profile\Client\System.Windows.Forms.dll</HintPath>
    </Reference>
    <Reference Include="WindowsFormsIntegration">
      <HintPath>..\..\..\..\..\Program Files\Reference Assemblies\Microsoft\Framework\v3.0\WindowsFormsIntegration.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="blank_world_map.png" />
    <Resource Include="Preloaded_GFX\EU4\mapmode_ProvincesOff.png" />
    <Resource Include="Preloaded_GFX\EU4\mapmode_ProvincesOn.png" />
    <Resource Include="Preloaded_GFX\VIC2\mapmode_PoliticalOff.png" />
    <Resource Include="Preloaded_GFX\VIC2\mapmode_PoliticalOn.png" />
    <Resource Include="Preloaded_GFX\VIC2\mapmode_ProvincesOff.png" />
    <Resource Include="Preloaded_GFX\VIC2\mapmode_ProvincesOn.png" />
    <Resource Include="Preloaded_GFX\VIC2\mapmode_TerrainOff.png" />
    <Resource Include="Preloaded_GFX\VIC2\mapmode_TerrainOn.png" />
    <Resource Include="Preloaded_GFX\VIC2\VIC2_Buttons(0).png" />
    <Resource Include="Preloaded_GFX\VIC2\VIC2_Buttons(1).png" />
    <Resource Include="Preloaded_GFX\VIC2\VIC2_Buttons(2).png" />
    <Resource Include="Preloaded_GFX\VIC2\VIC2_Buttons(3).png" />
    <Resource Include="Preloaded_GFX\VIC2\VIC2_Buttons(4).png" />
    <Resource Include="vic2_provinces.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
