//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradox_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paradox_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blank_world_map {
            get {
                object obj = ResourceManager.GetObject("blank_world_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///#========================= H E A D E R =========================
        ///
        ///color = { 255  255  255 }
        ///graphical_culture = EuropeanGC
        ///
        ///
        ///#========================= P A R T I E S =========================
        ///
        ///party = {
        ///name = &quot;JAN_conservative_92&quot;
        ///start_date = 1700.1.1
        ///end_date = 2000.1.1
        ///ideology = conservative
        ///economic_policy = interventionism
        ///trade_policy = protectionism
        ///religious_policy = moralism
        ///citizenship_policy = limited_citizenship
        ///war_policy = pro_military
        ///}
        ///party = {
        ///name = &quot;JAN_liberal_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jan_Mayen {
            get {
                return ResourceManager.GetString("Jan_Mayen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///#========================= H E A D E R =========================
        ///
        ///color = { 178  34  34 }
        ///graphical_culture = BritishGC
        ///
        ///
        ///#========================= P A R T I E S =========================
        ///
        ///party = {
        ///name = &quot;MAN_conservative_89&quot;
        ///start_date = 1700.1.1
        ///end_date = 2000.1.1
        ///ideology = conservative
        ///economic_policy = state_capitalism
        ///trade_policy = protectionism
        ///religious_policy = moralism
        ///citizenship_policy = limited_citizenship
        ///war_policy = jingoism
        ///social_policy = no_position_set
        ///}
        ///part [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mann {
            get {
                return ResourceManager.GetString("Mann", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///#========================= H E A D E R =========================
        ///
        ///color = { 240  230  140 }
        ///graphical_culture = EuropeanGC
        ///
        ///
        ///#========================= P A R T I E S =========================
        ///
        ///party = {
        ///name = &quot;PSK_conservative_92&quot;
        ///start_date = 1700.1.1
        ///end_date = 2000.1.1
        ///ideology = conservative
        ///economic_policy = interventionism
        ///trade_policy = protectionism
        ///religious_policy = moralism
        ///citizenship_policy = limited_citizenship
        ///war_policy = pro_military
        ///social_policy = no_position_set
        ///} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pskov {
            get {
                return ResourceManager.GetString("Pskov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Please keep tags sorted alphabetically when you add/remove country tags
        ///
        ///# Special countries...
        ///REB 	= 	&quot;countries/rebels.txt&quot;
        ///
        ///################LZ22&apos;s New Nations
        ///JAN		=&quot;countries/Jan Mayen.txt&quot;
        ///PSK		=&quot;countries/Pskov.txt&quot;
        ///MAN		=&quot;countries/Mann.txt&quot;
        ///
        ///##HoD Dominions
        ///dynamic_tags  = yes # any tags after this is considered dynamic dominions
        ///D01		= &quot;countries/D01.txt&quot;
        ///D02		= &quot;countries/D02.txt&quot;
        ///D03		= &quot;countries/D03.txt&quot;
        ///D04		= &quot;countries/D04.txt&quot;
        ///D05		= &quot;countries/D05.txt&quot;
        ///D06		= &quot;countries/D06.txt&quot;
        ///D07		= &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCountries {
            get {
                return ResourceManager.GetString("TestCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream VIC2_ValidClick {
            get {
                return ResourceManager.GetStream("VIC2_ValidClick", resourceCulture);
            }
        }
    }
}
